CREATE PROCEDURE [dbo].[getDoctorByID]
	@MaNhanVien INT OUTPUT
AS
BEGIN
	SELECT * FROM NHANVIEN
	INNER JOIN BACSI ON NHANVIEN.MaNhanVien = BACSI.MaNhanVien
	WHERE NHANVIEN.MaNhanVien = @MaNhanVien
	RETURN 1;
END