CREATE PROCEDURE [dbo].[getDoctorByName]
	@HoVaTen VARCHAR(255)
AS
BEGIN
	SELECT * FROM NHANVIEN
	INNER JOIN BACSI ON NHANVIEN.MaNhanVien = BACSI.MaNhanVien
	WHERE HoVaTen LIKE '%' + @HoVaTen + '%';
	RETURN 1;
END