CREATE PROCEDURE [dbo].[getGuardByName]
	@HoVaTen VARCHAR(255)
AS
BEGIN
	SELECT * FROM NHANVIEN
	INNER JOIN BAOVE ON NHANVIEN.MaNhanVien = BAOVE.MaNhanVien
	WHERE HoVaTen LIKE '%' + @HoVaTen + '%';
	RETURN 1;
END