CREATE PROCEDURE [dbo].[getGuardByID]
	@MaNhanVien INT OUTPUT
AS
BEGIN
	SELECT * FROM NHANVIEN 
	INNER JOIN BAOVE ON NHANVIEN.MaNhanVien = BAOVE.MaNhanVien
	WHERE NHANVIEN.MaNhanVien = @MaNhanVien
	RETURN 1;
END