CREATE PROCEDURE [dbo].[getNurseByPhoneNum]
	@SoDienThoai VARCHAR(50)
AS
BEGIN
	SELECT * FROM NHANVIEN
	INNER JOIN YTA ON NHANVIEN.MaNhanVien = YTA.MaNhanVien
	WHERE SoDienThoai = @SoDienThoai;
	RETURN 1;
END