CREATE PROCEDURE [dbo].[getNurseByID]
	@MaNhanVien INT OUTPUT
AS
BEGIN
	SELECT * FROM NHANVIEN 
	INNER JOIN YTA ON NHANVIEN.MaNhanVien = YTA.MaNhanVien
	WHERE NHANVIEN.MaNhanVien = @MaNhanVien
	RETURN 1;
END